# Generated by Django 4.2.1 on 2023-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pending", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="role",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ManyToManyField(
                blank=True, related_name="player", to="api.game"
            ),
        ),
    ]
