# Generated by Django 4.2.1 on 2023-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_game_player_role_player_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="pending",
        ),
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(default="Pending", max_length=10),
        ),
    ]
