# Generated by Django 4.2.1 on 2023-07-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_game_pending_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_action",
            field=models.CharField(default="", max_length=10),
        ),
    ]
