# Generated by Django 4.2.1 on 2023-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_game_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="round_number",
            field=models.SmallIntegerField(default=1),
        ),
    ]
